# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: selenium Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - uses: actions/checkout@v3
      if: success() || failure()
    - run: |
        cd testCases
        mkdir -p Reports
        pytest test_*.py --browser=chrome --html=Reports/report.html
        chmod 777 /home/runner/work/google_finance/google_finance/testCases/Reports/
      env:
        CONFIG_PATH: /home/runner/work/google_finance/google_finance/Configurations/config.ini

    - name: set output
      if: success() || failure()
      id: results
      run: echo "artifactPath=testCases/Reports/" >> $GITHUB_OUTPUT

    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: test-report
        path: ${{ steps.results.outputs.artifactPath }}
